version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: mapper-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

# Docker commands:
# docker run --name mapper-postgres -e POSTGRES_USER=postgis -e POSTGRES_PASSWORD=postgis -p 5432:5432 -d postgis/postgis:latest
# docker exec -ti some-postgis psql -U postgis